import { SPLATINK, type SplatinkKey } from "./splatink/paths";

// Display headings are Splatink delivered as outlined inline SVG paths — never a
// webfont (D-06). Path data is generated by scripts/generate-splatink.py from the
// licensed commercial .otf; the font file itself is neither committed nor served.
// Commercial desktop license is held (purchased 2026-07).

export default function SplatinkHeading({
  name,
  className = "",
  as: Tag = "h1",
}: {
  name: SplatinkKey;
  className?: string;
  /** Use "div" for decorative repeats so a page has a single <h1>. */
  as?: "h1" | "div";
}) {
  const { text, viewBox, d } = SPLATINK[name];
  const decorative = Tag === "div";
  return (
    <Tag className={className} {...(decorative ? { "aria-hidden": true } : {})}>
      <svg
        viewBox={viewBox}
        role={decorative ? undefined : "img"}
        aria-label={decorative ? undefined : text}
        fill="currentColor"
        className="h-full w-auto"
      >
        <path d={d} />
      </svg>
    </Tag>
  );
}
