import { SPLATINK, type SplatinkKey } from "./splatink/paths";

// Display headings are Splatink delivered as outlined inline SVG paths — never a
// webfont (D-06). Path data is generated by scripts/generate-splatink.mjs; the
// font file itself is neither committed nor served.
//
// ⚠️ Splatink is personal-use only until a commercial desktop license is held.
// Confirm before shipping. Outlining does not launder the license.

export default function SplatinkHeading({
  name,
  className = "",
}: {
  name: SplatinkKey;
  className?: string;
}) {
  const { text, viewBox, d } = SPLATINK[name];
  return (
    <h1 className={className}>
      <svg
        viewBox={viewBox}
        role="img"
        aria-label={text}
        fill="currentColor"
        className="h-full w-auto"
      >
        <path d={d} />
      </svg>
    </h1>
  );
}
