#!/usr/bin/env python3
"""Outlines Splatink display headings into SVG path data (spec D-06: inline SVG
paths only, never @font-face — no font file is committed or served).

Usage: python3 scripts/generate-splatink.py /path/to/Splatink.otf
Writes components/splatink/paths.ts. Re-run only when heading copy changes.

(Replaces generate-splatink.mjs — opentype.js emitted NaN coordinates for this
CFF font; fontTools parses it correctly.)

⚠️ Splatink (Måns Grebäck) is personal-use only without a commercial desktop
license — confirm the license is held before shipping these outlines.
"""

import json
import sys
from pathlib import Path

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

HEADINGS = {
    "collectibles": "Collectibles",
    "apparel": "Apparel",
    "about": "About Madbunny",
    "joinTheClub": "Join Madclub®",
}

SIZE = 100  # arbitrary; SVG scales


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit("Usage: python3 scripts/generate-splatink.py /path/to/Splatink.otf")

    font = TTFont(sys.argv[1])
    glyph_set = font.getGlyphSet()
    cmap = font.getBestCmap()
    upem = font["head"].unitsPerEm
    scale = SIZE / upem

    def glyph_name(ch: str) -> str | None:
        return cmap.get(ord(ch))

    entries = []
    for key, text in HEADINGS.items():
        svg_pen = SVGPathPen(glyph_set, ntos=lambda n: f"{n:.1f}")
        bounds_pen = BoundsPen(glyph_set)
        x = 0.0
        for ch in text:
            name = glyph_name(ch)
            if name is None:  # unmapped (e.g. plain space in some fonts)
                x += 0.33 * SIZE
                continue
            glyph = glyph_set[name]
            # ® renders small and baseline-aligned (mock), not at full cap size.
            s = scale * (0.42 if ch == "®" else 1)
            # Font units are y-up; SVG is y-down → flip y, then offset by pen x.
            transform = (s, 0, 0, -s, x, 0)
            glyph.draw(TransformPen(svg_pen, transform))
            glyph.draw(TransformPen(bounds_pen, transform))
            x += glyph.width * s

        if bounds_pen.bounds is None:
            sys.exit(f"No outlines produced for {text!r}")
        x1, y1, x2, y2 = bounds_pen.bounds
        pad = 2
        view_box = f"{x1 - pad:.1f} {y1 - pad:.1f} {x2 - x1 + 2 * pad:.1f} {y2 - y1 + 2 * pad:.1f}"
        d = svg_pen.getCommands()
        if "NaN" in d or "nan" in d:
            sys.exit(f"NaN coordinates in {text!r} — refusing to write")
        entries.append(
            f"  {key}: {{\n    text: {json.dumps(text)},\n"
            f"    viewBox: {json.dumps(view_box)},\n    d: {json.dumps(d)},\n  }},"
        )

    keys = " | ".join(json.dumps(k) for k in HEADINGS)
    body = "\n".join(entries)
    out = (
        "// GENERATED by scripts/generate-splatink.py — do not edit by hand.\n"
        "// Splatink display headings as outlined SVG path data (spec D-06).\n\n"
        f"export type SplatinkKey = {keys};\n\n"
        "export const SPLATINK: Record<SplatinkKey, { text: string; viewBox: string; d: string }> = {\n"
        f"{body}\n}};\n"
    )
    dest = Path(__file__).resolve().parent.parent / "components" / "splatink" / "paths.ts"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(out)
    print(f"Wrote {dest.relative_to(dest.parents[2])}: {' · '.join(HEADINGS.values())}")


if __name__ == "__main__":
    main()
